<?php

return [
    'export' => [
        'chunk_size' => env('POS_EXPORT_CHUNK_SIZE', 200),
    ],
    'ftp' => [
        'paths'  => [
            'input' => env('POS_PATH_INPUT_DIR', '/inputDataEC/'),
            'output' => env('POS_PATH_OUTPUT_DIR', '/outputDataEC/'),
            'torihikilog' => env('POS_PATH_INPUT_DIR_TORIHIKILOG', '/inputDataEC/'),
            'm_plu' => env('POS_PATH_OUTPUT_DIR_MPLU', '/outputDataEC/'),
            'm_zaiko' => env('POS_PATH_OUTPUT_DIR_MZAIKO', '/outputDataEC/'),
        ],
        'file_names' => [
            'torihikilog' => env('POS_FILE_NAME_TORIHIKILOG', 'TorihikiLog.xml'),
            'm_plu' => env('POS_FILE_NAME_MPLU', 'm_plu.txt'),
            'm_zaiko' => env('POS_FILE_NAME_MZAIKO', 'm_zaiko.txt'),
        ],
        'lock_files' => [
            'fit' => env('POS_LOCK_FILE_FIT', 'FILE_LOCK_FIT'),
            'ap' => env('POS_LOCK_FILE_AP', 'FILE_LOCK_AP'),
        ],
    ],
    'local' => [
        'file_names' => [
            'm_plu' => env('POS_FILE_NAME_TMP_MPLU', 'm_plu.tsv'),
            'm_zaiko' => env('POS_FILE_NAME_TMP_MZAIKO', 'm_zaiko.tsv'),
        ],
    ],
    'csv_indexs' => [
        'm_zaiko' => [
            'scancode_new' => 3,
            'zaiko_num'    => 6,
        ]
    ],
    'bill' => [
        'width' => 40,
    ],
    'tsv_headers' => [
        'm_plu' => [
            'misecode',
            'pluzokusei',
            'scancode_new',
            'scancode_old',
            'itemcode',
            'bumon',
            'hinsyu',
            'hinmei',
            'hinmei_kana',
            'pointjoflg',
            'nbkwbkjoflg',
            'urijoflg',
            'stanka1',
            'btanka1',
            'otanka1',
            'hbaika1',
            'price2date',
            'stanka2',
            'btanka2',
            'otanka2',
            'hbaika2',
            'genka',
            'zeikbn',
            'zeiptn',
            'tpnnwflg',
            'tpnnwgaku',
            'kaiinflg',
            'kaiinbaika',
            'tokubaiflg',
            'timeflg',
            'timestart',
            'timeend',
            'timebaika',
            'bmflg',
            'bmno',
            'bmpkgsuryo',
            'bmpkggaku',
            'seisansyacode',
            'tanpingroupno1',
            'tanpingroupno2',
            'urikage_date',
            'update_date',
            'update_time',
            'comment',
            'syain_hanbai_flg',
            'syain_kakaku',
            'tokusyu_hanbai_flg1',
            'tokusyu_kakaku1',
            'tokusyu_hanbai_flg2',
            'tokusyu_kakaku2',
            'tokusyu_hanbai_flg3',
            'tokusyu_kakaku3',
            'hontai_kakaku',
            'kakaku1',
            'kakaku2',
            'kakaku3',
            'description',
            'plu_url',
            'image_url',
            'hanbai_syudan',
            'print_flg',
            'size_code',
            'color_code',
            'reserve_chr1',
            'reserve_chr2',
            'reserve_chr3',
            'reserve_chr4',
            'reserve_chr5',
            'reserve_int1',
            'reserve_int2',
            'reserve_int3',
            'reserve_int4',
            'reserve_int5',
            'reserve_chr6',
            'reserve_chr7',
            'reserve_chr8',
            'reserve_chr9',
            'reserve_chr10',
            'reserve_int6',
            'reserve_int7',
            'reserve_int8',
            'reserve_int9',
            'reserve_int10',
            'hosthinmei',
            'kikakumei',
            'keiryoflg',
            'ItemKbn',
            'toppingflg',
            'jushokuflg',
            'orderprintflg',
            'orderhinmei',
            'freepriceflg'
        ],
        'm_zaiko' => [1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43
        ],
    ]
];
